### ISSUE TITLE
access denied, on hib write

### ISSUE THREAD

**Issue by edoziw** [shawenyao/the-key-v2#1]
Hello,
First off thanks for sharing your code.

I'm trying to use your example, to change the lights on the-key-v2 but I'm getting
```
 File "C:\Python311\Lib\site-packages\hid\__init__.py", line 148, in __hidcall
    raise HIDException(err)
hid.HIDException: WriteFile: (0x00000005) Access is denied.
```
Any ideas?

I used the hid.enumerate() to find my PATH, which seems similar to yours
```
PATH = b'\\\\?\\HID#VID_FEED&PID_0000&MI_00#7&16d7e0aa&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}'
```

The other paths for my device give `incorrect function` instead of `access denied` so I assume it is the right one

Note: I get access denied if I include `...\\KBD` from enumerate on the PATH or not..

I created a test .py file copied from your .py and simplified to just have it send mode 14
```
#.... your imports and methods with modified PATH

if __name__ == '__main__':
    send_msg(change_rgb_mode(14)) #14 swirl
```

I'm on windows 11 with python 3.11

I also tried it in powershell admin in case it needed admin rights..

Any suggestions or help would be appreciated.

Thanks

**Comment by shawenyao** [comment]
Hi edoziw: thanks for the interest. Did you flash the keyboard with the Vial-compatible [firmware](https://drop.com/buy/stack-overflow-the-key-v2-macropad/talk/2892369)? If so, is the Vial [GUI](https://get.vial.today/) able to detect and configure the keyboard? My script is merely a repackaging of the Vial source code so that should be a good way to debug.

**Comment by edoziw** [comment]
Thanks for the reply, I'll look into vial. Sorry for the huge lag in my response (just noticed this now...).

**Comment by shawenyao** [comment]
> Thanks for the reply, I'll look into vial. Sorry for the huge lag in my response (just noticed this now...).

Great. Let me know if it doesn't work.
